
import "./globals.css";
import { Metadata } from "next";
import "/public/assets/css/custom.css";
import 'sonner/dist/styles.css';
import { Poppins } from "next/font/google";
import { Providers } from "@/redux/provider";

export const metadata: Metadata = {
  title: "The Story of Handloom Jamdani",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png'
  },
  robots: "noindex, follow",
  other: {
    "x-ua-compatible": "ie=edge"
  }
};

export const viewport = "width=device-width, initial-scale=1.0, shrink-to-fit=no";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: 'swap'
});

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true} data-new-gr-c-s-check-loaded="14.1215.0" data-gr-ext-installed="">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}